/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Visitantes;

import Coneccion.CConexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Pablo
 */
public class SalidaVisitante extends javax.swing.JPanel {

    int contCarros = 20;
    int contMotos = 20;
    
    public SalidaVisitante() {
        initComponents();
        conteoCarro();
        conteoMoto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtNumParqueaderos1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtNumParqueaderos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtID = new javax.swing.JTextField();
        BtnTeset = new javax.swing.JButton();
        BtnSalida = new javax.swing.JButton();

        TxtNumParqueaderos1.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Parqueaderos Moto Disponibles:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Parqueaderos Carro Disponibles:");

        TxtNumParqueaderos.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro Visitantes");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Numero Documento:");

        TxtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDActionPerformed(evt);
            }
        });

        BtnTeset.setBackground(new java.awt.Color(153, 153, 153));
        BtnTeset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnTeset.setForeground(new java.awt.Color(255, 255, 255));
        BtnTeset.setText("Restaurar");
        BtnTeset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnTesetMouseClicked(evt);
            }
        });

        BtnSalida.setBackground(new java.awt.Color(255, 51, 51));
        BtnSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnSalida.setText("Salida");
        BtnSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalidaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtNumParqueaderos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNumParqueaderos1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnTeset, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNumParqueaderos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(TxtNumParqueaderos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTeset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIDActionPerformed

    private void BtnTesetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTesetMouseClicked
        
    }//GEN-LAST:event_BtnTesetMouseClicked

    private void BtnSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalidaMouseClicked
       int id = Integer.parseInt(TxtID.getText());

        try {
            Connection con = new CConexion().establecerConexion();
            PreparedStatement ps = con.prepareStatement("delete from RegistroVisitantes where idVisi = ?");

            ps.setInt(1, id);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Salido, Adios");

            ps.close();
            con.close();
            limpiar();
            conteoCarro();
            conteoMoto();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problemas para salidar compruebe el numero de documento");
        }
    }//GEN-LAST:event_BtnSalidaMouseClicked

    private void conteoCarro() {
        try {
            Connection con = new CConexion().establecerConexion();

            PreparedStatement ps = con.prepareStatement("SELECT COUNT(vehiculo) FROM RegistroVisitantes WHERE vehiculo = 'Carro'");

            ResultSet rs = ps.executeQuery(); 

            if (rs.next()) { 
                int numeroRegistros = rs.getInt(1); 
                int resl = contCarros - numeroRegistros; 
                String Mostrar = Integer.toString(resl); 
                TxtNumParqueaderos.setText(Mostrar); 
            }

            rs.close(); 
            ps.close(); 
            con.close(); 
        } catch (Exception e) {
        }
    }
    
    private void conteoMoto(){
         try {
            Connection con = new CConexion().establecerConexion();

            PreparedStatement ps = con.prepareStatement("SELECT COUNT(vehiculo) FROM RegistroVisitantes WHERE vehiculo = 'Moto'");

            ResultSet rs = ps.executeQuery(); 

            if (rs.next()) { 
                int numeroRegistros = rs.getInt(1); 
                int resl = contMotos - numeroRegistros; 
                String Mostrar = Integer.toString(resl); 
                TxtNumParqueaderos1.setText(Mostrar); 
            }

            rs.close(); 
            ps.close(); 
            con.close(); 
        } catch (Exception e) {
        }
    }
    
    private void limpiar() {
        TxtID.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalida;
    private javax.swing.JButton BtnTeset;
    private javax.swing.JTextField TxtID;
    private javax.swing.JTextField TxtNumParqueaderos;
    private javax.swing.JTextField TxtNumParqueaderos1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
