/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.CanchaSintetica.CancelarReservas;
import GUI.CanchaSintetica.ReservarCanchaSintetica;
import GUI.PQRSD.RegistroPQRSD;
import GUI.SalonSocial.ListadoReservasSalonSocial;
import GUI.SalonSocial.ReservaSalonSocial;
import GUI.Visitantes.ImprimirVisitantes;
import GUI.Visitantes.RegistroVisitantes;
import GUI.Visitantes.SalidaVisitante;
import GUI.formulariosResidentes.Juridico;
import GUI.formulariosResidentes.Nat;
import GUI.ZonaBQQ.PagoDañosZonaBQQ;
import GUI.ZonaBQQ.ListadoReservaZonaBQQ;
import GUI.ZonaBQQ.FormularioReservaZonaBQQ;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Pablo
 */
public class Formulario extends javax.swing.JFrame {

    private String valor;

    /**
     * Creates new form Formulario
     */
    public Formulario(String valor) {
        initComponents();
        this.valor = valor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pprincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        ResidenteNatural = new javax.swing.JMenu();
        ResidenteJuridico = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        RegistroVisitantes = new javax.swing.JMenu();
        SalidaVisitantes = new javax.swing.JMenu();
        ImprimirListado = new javax.swing.JMenu();
        SalonSocial = new javax.swing.JMenu();
        ReservaSalonSocial = new javax.swing.JMenu();
        ListadoReservas = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        ReservarZonaBQQ = new javax.swing.JMenu();
        ListadoReservasZonaBQQ = new javax.swing.JMenu();
        PagosDañosBQQ = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        ReservarCancha = new javax.swing.JMenu();
        CancelarReserva = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        RegistrarPQRSD = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PprincipalLayout = new javax.swing.GroupLayout(Pprincipal);
        Pprincipal.setLayout(PprincipalLayout);
        PprincipalLayout.setHorizontalGroup(
            PprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );
        PprincipalLayout.setVerticalGroup(
            PprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        jMenu2.setText("Registro Residentes");

        ResidenteNatural.setText("Residente Natural");
        ResidenteNatural.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResidenteNaturalMouseClicked(evt);
            }
        });
        jMenu2.add(ResidenteNatural);

        ResidenteJuridico.setText("Residente Juridico");
        ResidenteJuridico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResidenteJuridicoMouseClicked(evt);
            }
        });
        jMenu2.add(ResidenteJuridico);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Visitantes");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        RegistroVisitantes.setText("Registro");
        RegistroVisitantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistroVisitantesMouseClicked(evt);
            }
        });
        jMenu1.add(RegistroVisitantes);

        SalidaVisitantes.setText("Salida");
        SalidaVisitantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalidaVisitantesMouseClicked(evt);
            }
        });
        jMenu1.add(SalidaVisitantes);

        ImprimirListado.setText("Imprimir Listado");
        ImprimirListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImprimirListadoMouseClicked(evt);
            }
        });
        jMenu1.add(ImprimirListado);

        jMenuBar1.add(jMenu1);

        SalonSocial.setText("Salon Social");

        ReservaSalonSocial.setText("Reservar Salon Social");
        ReservaSalonSocial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservaSalonSocialMouseClicked(evt);
            }
        });
        SalonSocial.add(ReservaSalonSocial);

        ListadoReservas.setText("Listado Reservas");
        ListadoReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListadoReservasMouseClicked(evt);
            }
        });
        SalonSocial.add(ListadoReservas);

        jMenuBar1.add(SalonSocial);

        jMenu4.setText("Zona BQQ");

        ReservarZonaBQQ.setText("Reservar Zona BQQ");
        ReservarZonaBQQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservarZonaBQQMouseClicked(evt);
            }
        });
        jMenu4.add(ReservarZonaBQQ);

        ListadoReservasZonaBQQ.setText("Listado Reservas");
        ListadoReservasZonaBQQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListadoReservasZonaBQQMouseClicked(evt);
            }
        });
        jMenu4.add(ListadoReservasZonaBQQ);

        PagosDañosBQQ.setText("Pago Daños Zona BQQ");
        PagosDañosBQQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PagosDañosBQQMouseClicked(evt);
            }
        });
        jMenu4.add(PagosDañosBQQ);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Cancha Sintetica");

        ReservarCancha.setText("Reservar Cancha");
        ReservarCancha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservarCanchaMouseClicked(evt);
            }
        });
        jMenu3.add(ReservarCancha);

        CancelarReserva.setText("Cancelar Reserva");
        CancelarReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarReservaMouseClicked(evt);
            }
        });
        jMenu3.add(CancelarReserva);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("PQRSD");

        RegistrarPQRSD.setText("Registrar PQRSD");
        RegistrarPQRSD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarPQRSDMouseClicked(evt);
            }
        });
        jMenu5.add(RegistrarPQRSD);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ListadoReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListadoReservasMouseClicked
        String user = "Admin";
        if (valor.equals(user)) {
            ListadoReservasSalonSocial l = new ListadoReservasSalonSocial();
            l.setSize(700, 600);
            Pprincipal.removeAll();
            Pprincipal.add(l);
            Pprincipal.revalidate();
            Pprincipal.repaint();
        } else {
            JOptionPane.showMessageDialog(null, "No tiene permiso para ver este listado");
        }

    }//GEN-LAST:event_ListadoReservasMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

    }//GEN-LAST:event_jMenu1MouseClicked

    private void RegistroVisitantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroVisitantesMouseClicked
        RegistroVisitantes r = new RegistroVisitantes();
        r.setSize(600, 500);
        Pprincipal.removeAll();
        Pprincipal.add(r);
        Pprincipal.revalidate();
        Pprincipal.repaint();
    }//GEN-LAST:event_RegistroVisitantesMouseClicked

    private void SalidaVisitantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalidaVisitantesMouseClicked
        SalidaVisitante s = new SalidaVisitante();
        s.setSize(600, 500);
        Pprincipal.removeAll();
        Pprincipal.add(s);
        Pprincipal.revalidate();
        Pprincipal.repaint();
    }//GEN-LAST:event_SalidaVisitantesMouseClicked

    private void ResidenteNaturalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResidenteNaturalMouseClicked
        Nat n = new Nat();
        n.setSize(600, 500);
        Pprincipal.removeAll();
        Pprincipal.add(n);
        Pprincipal.revalidate();
        Pprincipal.repaint();
    }//GEN-LAST:event_ResidenteNaturalMouseClicked

    private void ResidenteJuridicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResidenteJuridicoMouseClicked
        Juridico j = new Juridico();
        j.setSize(600, 500);
        Pprincipal.removeAll();
        Pprincipal.add(j);
        Pprincipal.revalidate();
        Pprincipal.repaint();
    }//GEN-LAST:event_ResidenteJuridicoMouseClicked

    private void ReservarZonaBQQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservarZonaBQQMouseClicked
        FormularioReservaZonaBQQ f = new FormularioReservaZonaBQQ();
        f.setSize(660, 538);
        Pprincipal.removeAll();
        Pprincipal.add(f);
        Pprincipal.revalidate();
        Pprincipal.repaint();
    }//GEN-LAST:event_ReservarZonaBQQMouseClicked

    private void ListadoReservasZonaBQQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListadoReservasZonaBQQMouseClicked
        ListadoReservaZonaBQQ l = new ListadoReservaZonaBQQ();
        l.setSize(660, 538);
        Pprincipal.removeAll();
        Pprincipal.add(l);
        Pprincipal.revalidate();
        Pprincipal.repaint();
    }//GEN-LAST:event_ListadoReservasZonaBQQMouseClicked

    private void PagosDañosBQQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PagosDañosBQQMouseClicked
        PagoDañosZonaBQQ p = new PagoDañosZonaBQQ();
        p.setSize(660, 538);
        Pprincipal.removeAll();
        Pprincipal.add(p);
        Pprincipal.revalidate();
        Pprincipal.repaint();
    }//GEN-LAST:event_PagosDañosBQQMouseClicked

    private void ReservaSalonSocialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservaSalonSocialMouseClicked
        ReservaSalonSocial r = new ReservaSalonSocial();
        r.setSize(877, 715);
        Pprincipal.removeAll();
        Pprincipal.add(r);
        Pprincipal.revalidate();
        Pprincipal.repaint();
    }//GEN-LAST:event_ReservaSalonSocialMouseClicked

    private void ImprimirListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImprimirListadoMouseClicked
        ImprimirVisitantes i = new ImprimirVisitantes();
        i.setSize(877, 715);
        Pprincipal.removeAll();
        Pprincipal.add(i);
        Pprincipal.revalidate();
        Pprincipal.repaint();
    }//GEN-LAST:event_ImprimirListadoMouseClicked

    private void ReservarCanchaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservarCanchaMouseClicked
        ReservarCanchaSintetica r = new ReservarCanchaSintetica();
        r.setSize(877, 715);
        Pprincipal.removeAll();
        Pprincipal.add(r);
        Pprincipal.revalidate();
        Pprincipal.repaint();
    }//GEN-LAST:event_ReservarCanchaMouseClicked

    private void CancelarReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarReservaMouseClicked
        CancelarReservas c = new CancelarReservas();
        c.setSize(877, 715);
        Pprincipal.removeAll();
        Pprincipal.add(c);
        Pprincipal.revalidate();
        Pprincipal.repaint();
    }//GEN-LAST:event_CancelarReservaMouseClicked

    private void RegistrarPQRSDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarPQRSDMouseClicked
        RegistroPQRSD r = new RegistroPQRSD();
        r.setVisible(true);
    }//GEN-LAST:event_RegistrarPQRSDMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CancelarReserva;
    private javax.swing.JMenu ImprimirListado;
    private javax.swing.JMenu ListadoReservas;
    private javax.swing.JMenu ListadoReservasZonaBQQ;
    private javax.swing.JMenu PagosDañosBQQ;
    private javax.swing.JPanel Pprincipal;
    private javax.swing.JMenu RegistrarPQRSD;
    private javax.swing.JMenu RegistroVisitantes;
    private javax.swing.JMenu ReservaSalonSocial;
    private javax.swing.JMenu ReservarCancha;
    private javax.swing.JMenu ReservarZonaBQQ;
    private javax.swing.JMenu ResidenteJuridico;
    private javax.swing.JMenu ResidenteNatural;
    private javax.swing.JMenu SalidaVisitantes;
    private javax.swing.JMenu SalonSocial;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
